```sql
-- ============================================================
-- Sancta Historia
-- Snapshot da estrutura atual do banco de dados
-- Data: 2026-06-11
-- Banco: Supabase / PostgreSQL
--
-- Observação:
-- Este arquivo documenta a estrutura esperada do banco.
-- Não execute em produção sem revisar, pois algumas tabelas
-- já podem existir no Supabase.
-- ============================================================

-- ============================================================
-- TABELA: saints
-- ============================================================

create table if not exists public.saints (
  id bigint generated by default as identity primary key,

  name text not null,
  birth_year integer,
  death_year integer,
  birth_place text,
  death_place text,

  short_description text,
  biography text,

  feast_day text,
  canonization_year integer,
  canonization_note text,

  patron_of text,
  image_url text,
  religious_order text,
  category text,
  famous_quote text,

  birth_year_note text,
  death_year_note text,
  historical_importance text,
  sources text,

  created_at timestamp with time zone default now()
);

-- ============================================================
-- TABELA: locations
-- ============================================================

create table if not exists public.locations (
  id bigint generated by default as identity primary key,

  saint_id bigint references public.saints(id) on delete cascade,

  location_name text not null,
  latitude numeric,
  longitude numeric,

  start_year integer,
  end_year integer,

  description text,

  created_at timestamp with time zone default now()
);

-- ============================================================
-- TABELA: popes
-- ============================================================

create table if not exists public.popes (
  id bigint generated by default as identity primary key,

  name text not null,
  start_year integer,
  end_year integer,
  nationality text,
  description text,

  created_at timestamp with time zone default now()
);

-- ============================================================
-- TABELA: historical_events
-- ============================================================

create table if not exists public.historical_events (
  id bigint generated by default as identity primary key,

  title text not null,
  year integer,
  category text,
  description text,

  created_at timestamp with time zone default now()
);

-- ============================================================
-- ÍNDICES
-- ============================================================

create index if not exists idx_saints_birth_year
on public.saints(birth_year);

create index if not exists idx_saints_death_year
on public.saints(death_year);

create index if not exists idx_saints_name
on public.saints(name);

create index if not exists idx_locations_saint_id
on public.locations(saint_id);

create index if not exists idx_locations_years
on public.locations(start_year, end_year);

create index if not exists idx_popes_years
on public.popes(start_year, end_year);

create index if not exists idx_historical_events_year
on public.historical_events(year);

-- ============================================================
-- RLS
-- ============================================================

alter table public.saints enable row level security;
alter table public.locations enable row level security;
alter table public.popes enable row level security;
alter table public.historical_events enable row level security;

-- ============================================================
-- POLÍTICAS DE LEITURA PÚBLICA
-- ============================================================

drop policy if exists "Public read saints" on public.saints;

create policy "Public read saints"
on public.saints
for select
to anon
using (true);

drop policy if exists "Public read locations" on public.locations;

create policy "Public read locations"
on public.locations
for select
to anon
using (true);

drop policy if exists "Public read popes" on public.popes;

create policy "Public read popes"
on public.popes
for select
to anon
using (true);

drop policy if exists "Public read historical_events" on public.historical_events;

create policy "Public read historical_events"
on public.historical_events
for select
to anon
using (true);

-- ============================================================
-- CONSULTAS DE CONFERÊNCIA
-- ============================================================

-- Total de santos
-- select count(*) from public.saints;

-- Total de locais
-- select count(*) from public.locations;

-- Total de papas
-- select count(*) from public.popes;

-- Total de eventos históricos
-- select count(*) from public.historical_events;

-- Santos sem local cadastrado
-- select s.id, s.name
-- from public.saints s
-- left join public.locations l on l.saint_id = s.id
-- where l.id is null
-- order by s.birth_year;

-- Locais sem santo vinculado
-- select l.*
-- from public.locations l
-- left join public.saints s on s.id = l.saint_id
-- where s.id is null;

-- Santos duplicados por nome
-- select name, count(*)
-- from public.saints
-- group by name
-- having count(*) > 1
-- order by name;
```
