begin;

create table public.map_landmarks (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.places(id) on delete cascade,
  kind text not null,
  title text not null,
  description text,
  start_year integer,
  end_year integer,
  source_url text,
  is_published boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint map_landmarks_kind_values
    check (kind in ('important_city', 'episcopal_see', 'pilgrimage_site')),
  constraint map_landmarks_title_nonempty
    check (trim(title) <> ''),
  constraint map_landmarks_period_valid
    check (end_year is null or start_year is null or end_year >= start_year),
  constraint map_landmarks_place_kind_key
    unique (place_id, kind)
);

create index map_landmarks_timeline_idx
  on public.map_landmarks(start_year, end_year)
  where is_published;

create trigger map_landmarks_set_updated_at
before update on public.map_landmarks
for each row execute function public.set_updated_at();

alter table public.map_landmarks enable row level security;

create policy "Public landmarks are readable"
on public.map_landmarks
for select
to anon, authenticated
using (is_published);

grant select on public.map_landmarks to anon, authenticated;

insert into public.map_landmarks (
  place_id,
  kind,
  title,
  description,
  start_year,
  source_url
)
select
  places.id,
  seed.kind,
  seed.title,
  seed.description,
  seed.start_year,
  seed.source_url
from (
  values
    ('Roma', 'important_city', 'Roma', 'Centro político do mundo romano e cidade profundamente ligada à história da Igreja.', -753, 'https://www.vatican.va/roman_curia/pontifical_commissions/archeo/inglese/documents/rc_com_archeo_doc_20011010_cataccrist_en.html'),
    ('Jerusalém', 'important_city', 'Jerusalém', 'Cidade da Paixão, Morte e Ressurreição de Jesus Cristo e do nascimento da Igreja em Pentecostes.', -1000, 'https://www.vatican.va/content/francesco/en/speeches/2014/may/documents/papa-francesco_20140526_terra-santa-gran-mufti.html'),
    ('Alexandria', 'important_city', 'Alexandria', 'Grande centro cultural do Mediterrâneo antigo e referência da Igreja no Egito.', -331, 'https://www.vatican.va/content/benedict-xvi/en/audiences/2007/documents/hf_ben-xvi_aud_20070418.html'),
    ('Antioquia', 'important_city', 'Antioquia', 'Importante centro apostólico onde os discípulos receberam pela primeira vez o nome de cristãos.', -300, 'https://www.vatican.va/archive/ENG0839/__PXR.HTM'),
    ('Constantinopla/Istambul', 'important_city', 'Constantinopla', 'Capital imperial fundada por Constantino e centro decisivo da história cristã oriental.', 330, 'https://www.vatican.va/content/benedict-xvi/en/speeches/2006/november/documents/hf_ben-xvi_spe_20061130_divine-liturgy.html'),
    ('Roma', 'episcopal_see', 'Sé de Roma', 'Igreja de Roma, ligada ao testemunho e ao martírio dos apóstolos São Pedro e São Paulo.', 64, 'https://www.vatican.va/content/benedict-xvi/en/homilies/2008/documents/hf_ben-xvi_hom_20080628_vespri.html'),
    ('Jerusalém', 'episcopal_see', 'Sé de Jerusalém', 'Igreja-mãe de Jerusalém, presidida nos tempos apostólicos por São Tiago.', 33, 'https://www.vatican.va/archive/ENG0839/__PYA.HTM'),
    ('Antioquia', 'episcopal_see', 'Sé de Antioquia', 'Antiga sé apostólica associada à missão de São Pedro e São Paulo.', 37, 'https://www.vatican.va/archive/ENG0839/__PXR.HTM'),
    ('Alexandria', 'episcopal_see', 'Sé de Alexandria', 'Uma das grandes sedes episcopais da Igreja antiga.', 42, 'https://www.vatican.va/content/benedict-xvi/en/audiences/2007/documents/hf_ben-xvi_aud_20070418.html'),
    ('Constantinopla/Istambul', 'episcopal_see', 'Sé de Constantinopla', 'Sede episcopal da Nova Roma e centro dos concílios ecumênicos da Antiguidade.', 381, 'https://www.vatican.va/content/benedict-xvi/en/speeches/2006/november/documents/hf_ben-xvi_spe_20061130_divine-liturgy.html'),
    ('Cantuária/Canterbury', 'episcopal_see', 'Sé de Cantuária', 'Sede estabelecida na missão de Santo Agostinho de Cantuária entre os povos ingleses.', 597, 'https://www.vatican.va/content/benedict-xvi/en/audiences/2009/documents/hf_ben-xvi_aud_20090603.html'),
    ('Jerusalém', 'pilgrimage_site', 'Jerusalém, Cidade Santa', 'Destino de peregrinação aos lugares da vida, Paixão, Morte e Ressurreição de Jesus.', 33, 'https://www.vatican.va/content/francesco/en/speeches/2014/may/documents/papa-francesco_20140526_terra-santa-gran-mufti.html'),
    ('Roma/Vaticano', 'pilgrimage_site', 'Túmulo de São Pedro', 'Lugar de peregrinação e veneração junto ao túmulo do apóstolo São Pedro.', 326, 'https://www.vatican.va/various/basiliche/san_pietro/index_it.html'),
    ('Mylapore/Chennai', 'pilgrimage_site', 'Santuário de São Tomé', 'Lugar tradicionalmente ligado ao martírio e ao túmulo do apóstolo São Tomé.', 72, 'https://www.vatican.va/content/francesco/en/speeches/2024/june/documents/20240626-giubileo-san-tommaso.html'),
    ('Monte Cassino', 'pilgrimage_site', 'Abadia de Monte Cassino', 'Mosteiro fundado por São Bento e referência espiritual da tradição beneditina.', 529, 'https://www.vatican.va/content/benedict-xvi/en/audiences/2008/documents/hf_ben-xvi_aud_20080409.html'),
    ('Santiago de Compostela', 'pilgrimage_site', 'Santiago de Compostela', 'Antigo destino de peregrinação ligado ao túmulo do apóstolo São Tiago Maior.', 813, 'https://www.vatican.va/content/benedict-xvi/en/speeches/2010/november/documents/hf_ben-xvi_spe_20101106_intervista.html'),
    ('Assis', 'pilgrimage_site', 'Assis', 'Cidade de São Francisco e Santa Clara, visitada por peregrinos de todo o mundo.', 1226, 'https://www.vatican.va/content/benedict-xvi/en/speeches/2007/june/documents/hf_ben-xvi_spe_20070617_assisi.html'),
    ('Pádua', 'pilgrimage_site', 'Basílica de Santo Antônio', 'Destino de peregrinação junto ao túmulo de Santo Antônio de Pádua.', 1231, 'https://www.vatican.va/content/john-paul-ii/en/speeches/1982/september/documents/hf_jp-ii_spe_19820912_cittadinanza-padova.html')
) as seed(place_name, kind, title, description, start_year, source_url)
join public.places on places.name = seed.place_name
on conflict (place_id, kind) do update set
  title = excluded.title,
  description = excluded.description,
  start_year = excluded.start_year,
  source_url = excluded.source_url,
  is_published = true;

create view public.timeline_map_landmarks
with (security_invoker = true)
as
select
  landmarks.id,
  landmarks.kind,
  landmarks.title,
  landmarks.description,
  landmarks.start_year,
  landmarks.end_year,
  places.name as location_name,
  places.latitude,
  places.longitude
from public.map_landmarks as landmarks
join public.places on places.id = landmarks.place_id
where landmarks.is_published
  and places.is_published
  and places.latitude is not null
  and places.longitude is not null;

grant select on public.timeline_map_landmarks to anon, authenticated;

commit;
