-- Sancta Historia
-- Cria o catálogo de paróquias (cadastro manual, para exibição futura no
-- mapa) e liga o perfil do usuário à paróquia a que pertence.

begin;

create table if not exists public.parishes (
  id bigint generated by default as identity primary key,
  name text not null,
  diocese text,
  address text,
  city text,
  state text,
  country text,
  latitude double precision,
  longitude double precision,
  is_published boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint parishes_name_nonempty
    check (trim(name) <> ''),
  constraint parishes_latitude_range
    check (latitude is null or latitude between -90 and 90),
  constraint parishes_longitude_range
    check (longitude is null or longitude between -180 and 180),
  constraint parishes_coordinates_complete
    check ((latitude is null) = (longitude is null))
);

create index if not exists parishes_published_name_idx
  on public.parishes(name)
  where is_published;

drop trigger if exists parishes_set_updated_at on public.parishes;
create trigger parishes_set_updated_at
before update on public.parishes
for each row
execute function public.set_updated_at();

alter table public.parishes enable row level security;

drop policy if exists "Public read published parishes" on public.parishes;
create policy "Public read published parishes"
on public.parishes
for select
to anon, authenticated
using (is_published);

grant select on public.parishes to anon, authenticated;

alter table public.profiles
  add column if not exists favorite_parish_id bigint
    references public.parishes(id)
    on delete set null;

comment on table public.parishes is
  'Paróquias cadastradas manualmente (nome, diocese, endereço, coordenadas). Fonte para o seletor de perfil e, futuramente, para exibição no mapa.';
comment on column public.profiles.favorite_parish_id is
  'Paróquia à qual o usuário pertence, selecionada a partir de public.parishes. Só pode ser uma das já cadastradas (sem cadastro self-service pelo usuário).';

commit;

select
  (select count(*) from public.parishes) as paroquias_cadastradas;
