create extension if not exists postgis with schema extensions;

create table public.ecclesiastical_sources (
  id bigint generated by default as identity primary key,
  title text not null,
  publisher text not null,
  url text not null unique,
  source_type text not null default 'official'
    check (source_type in ('official', 'canonical', 'statistical', 'geocoder')),
  checked_at date not null default current_date,
  notes text,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.ecclesiastical_jurisdictions (
  id bigint generated by default as identity primary key,
  slug text not null unique
    check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null,
  canonical_type text not null check (
    canonical_type in (
      'holy_see',
      'ecclesiastical_province',
      'patriarchate',
      'major_archiepiscopal_church',
      'metropolitan_archdiocese',
      'archdiocese',
      'diocese',
      'eparchy',
      'territorial_prelature',
      'territorial_abbey',
      'apostolic_vicariate',
      'apostolic_prefecture',
      'apostolic_administration',
      'exarchate',
      'ordinariate',
      'military_ordinariate',
      'mission_sui_iuris',
      'deanery',
      'forane_vicariate',
      'parish',
      'quasi_parish'
    )
  ),
  tradition text not null default 'latin'
    check (tradition in ('latin', 'eastern')),
  church_sui_iuris text,
  country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  status text not null default 'active'
    check (status in ('active', 'suppressed', 'historical')),
  erected_year integer,
  suppressed_year integer,
  description text,
  official_url text,
  primary_source_id bigint references public.ecclesiastical_sources(id)
    on delete set null,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    suppressed_year is null
    or erected_year is null
    or suppressed_year >= erected_year
  )
);

create table public.ecclesiastical_relations (
  id bigint generated by default as identity primary key,
  subject_jurisdiction_id bigint not null
    references public.ecclesiastical_jurisdictions(id) on delete cascade,
  object_jurisdiction_id bigint not null
    references public.ecclesiastical_jurisdictions(id) on delete cascade,
  relation_type text not null check (
    relation_type in (
      'belongs_to_province',
      'metropolitan_of',
      'suffragan_of',
      'directly_subject_to_holy_see',
      'belongs_to_sui_iuris_church',
      'subdivision_of'
    )
  ),
  valid_from_year integer,
  valid_to_year integer,
  primary_source_id bigint references public.ecclesiastical_sources(id)
    on delete set null,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  unique (
    subject_jurisdiction_id,
    object_jurisdiction_id,
    relation_type,
    valid_from_year
  ),
  check (subject_jurisdiction_id <> object_jurisdiction_id),
  check (
    valid_to_year is null
    or valid_from_year is null
    or valid_to_year >= valid_from_year
  )
);

create table public.ecclesiastical_sites (
  id bigint generated by default as identity primary key,
  jurisdiction_id bigint not null
    references public.ecclesiastical_jurisdictions(id) on delete cascade,
  slug text not null unique
    check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null,
  site_type text not null check (
    site_type in (
      'apostolic_see',
      'cathedral',
      'co_cathedral',
      'curia',
      'parish_church',
      'chapel',
      'mission_station',
      'shrine'
    )
  ),
  address text,
  locality text,
  admin_area text,
  country_code text not null check (country_code ~ '^[A-Z]{2}$'),
  location extensions.geography(point, 4326) not null,
  min_zoom real not null default 8 check (min_zoom >= 0 and min_zoom <= 22),
  display_rank smallint not null default 100 check (display_rank >= 0),
  valid_from_year integer,
  valid_to_year integer,
  official_url text,
  location_accuracy text not null default 'exact'
    check (location_accuracy in ('exact', 'geocoded_address', 'approximate')),
  primary_source_id bigint references public.ecclesiastical_sources(id)
    on delete set null,
  is_primary boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    valid_to_year is null
    or valid_from_year is null
    or valid_to_year >= valid_from_year
  )
);

create index ecclesiastical_sites_location_gix
  on public.ecclesiastical_sites using gist (location);
create index ecclesiastical_sites_zoom_year_idx
  on public.ecclesiastical_sites (min_zoom, valid_from_year, valid_to_year)
  where is_published;
create index ecclesiastical_relations_subject_idx
  on public.ecclesiastical_relations (subject_jurisdiction_id);
create index ecclesiastical_relations_object_idx
  on public.ecclesiastical_relations (object_jurisdiction_id);

alter table public.ecclesiastical_sources enable row level security;
alter table public.ecclesiastical_jurisdictions enable row level security;
alter table public.ecclesiastical_relations enable row level security;
alter table public.ecclesiastical_sites enable row level security;

create policy "Public can read published ecclesiastical sources"
  on public.ecclesiastical_sources for select
  to anon, authenticated
  using (is_published);

create policy "Public can read published ecclesiastical jurisdictions"
  on public.ecclesiastical_jurisdictions for select
  to anon, authenticated
  using (is_published);

create policy "Public can read published ecclesiastical relations"
  on public.ecclesiastical_relations for select
  to anon, authenticated
  using (is_published);

create policy "Public can read published ecclesiastical sites"
  on public.ecclesiastical_sites for select
  to anon, authenticated
  using (is_published);

grant select on public.ecclesiastical_sources to anon, authenticated;
grant select on public.ecclesiastical_jurisdictions to anon, authenticated;
grant select on public.ecclesiastical_relations to anon, authenticated;
grant select on public.ecclesiastical_sites to anon, authenticated;

create or replace function public.ecclesiastical_points_in_view(
  min_long double precision,
  min_lat double precision,
  max_long double precision,
  max_lat double precision,
  map_zoom double precision,
  selected_year integer default null
)
returns table (
  id bigint,
  name text,
  site_type text,
  canonical_type text,
  jurisdiction_name text,
  latitude double precision,
  longitude double precision,
  address text,
  locality text,
  country_code text,
  official_url text,
  min_zoom real
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    site.id,
    site.name,
    site.site_type,
    jurisdiction.canonical_type,
    jurisdiction.name as jurisdiction_name,
    extensions.st_y(site.location::extensions.geometry) as latitude,
    extensions.st_x(site.location::extensions.geometry) as longitude,
    site.address,
    site.locality,
    site.country_code,
    coalesce(site.official_url, jurisdiction.official_url) as official_url,
    site.min_zoom
  from public.ecclesiastical_sites as site
  join public.ecclesiastical_jurisdictions as jurisdiction
    on jurisdiction.id = site.jurisdiction_id
  where site.is_published
    and jurisdiction.is_published
    and site.min_zoom <= map_zoom
    and (
      selected_year is null
      or (
        (site.valid_from_year is null or site.valid_from_year <= selected_year)
        and (site.valid_to_year is null or site.valid_to_year >= selected_year)
        and (
          jurisdiction.erected_year is null
          or jurisdiction.erected_year <= selected_year
        )
        and (
          jurisdiction.suppressed_year is null
          or jurisdiction.suppressed_year >= selected_year
        )
      )
    )
    and site.location operator(extensions.&&)
      extensions.st_setsrid(
        extensions.st_makebox2d(
          extensions.st_point(min_long, min_lat),
          extensions.st_point(max_long, max_lat)
        ),
        4326
      )
  order by site.display_rank, site.min_zoom, site.name
  limit 750
$$;

revoke all on function public.ecclesiastical_points_in_view(
  double precision,
  double precision,
  double precision,
  double precision,
  double precision,
  integer
) from public;
grant execute on function public.ecclesiastical_points_in_view(
  double precision,
  double precision,
  double precision,
  double precision,
  double precision,
  integer
) to anon, authenticated;

insert into public.ecclesiastical_sources
  (title, publisher, url, source_type, checked_at, notes)
values
  (
    'Origens e natureza do Estado da Cidade do Vaticano',
    'Estado da Cidade do Vaticano',
    'https://www.vaticanstate.va/en/state-and-government/general-informations/origins-and-characteristic.html',
    'official',
    '2026-07-26',
    'Distingue a personalidade internacional da Santa Sé do território do Estado da Cidade do Vaticano.'
  ),
  (
    'Estrutura administrativa e pastoral da CNBB',
    'Conferência Nacional dos Bispos do Brasil',
    'https://www.cnbb.org.br/a-estrutura-administrativa-e-pastoral-da-cnbb-tem-uma-matriz-e-18-unidades-regionais/',
    'official',
    '2026-07-26',
    'Registra a Província Eclesiástica de Brasília e suas dioceses sufragâneas.'
  ),
  (
    'Paróquias da Arquidiocese de Brasília',
    'Arquidiocese de Brasília',
    'https://arqbrasilia.com.br/paroquias/',
    'official',
    '2026-07-26',
    'Catálogo oficial de paróquias, vicariatos, setores e cidades.'
  ),
  (
    'Catedral Nossa Senhora Imaculada Conceição',
    'Diocese de Formosa',
    'https://diocesedeformosa.com.br/paroquia/catedralnossasenhoraimaculadaconceicao/',
    'official',
    '2026-07-26',
    'Identifica a igreja-mãe, o endereço e a história da Diocese de Formosa.'
  ),
  (
    'Santuário Nossa Senhora de Fátima',
    'Arquidiocese de Brasília',
    'https://arqbrasilia.com.br/todas_paroquias/nossa-senhora-de-fatima/',
    'official',
    '2026-07-26',
    'Página oficial da paróquia e do santuário na Asa Sul.'
  ),
  (
    'Paróquia São Rafael Arcanjo',
    'Arquidiocese de Brasília',
    'https://arqbrasilia.com.br/todas_paroquias/paroquia-sao-rafael-arcanjo/',
    'official',
    '2026-07-26',
    'Página oficial da paróquia no Recanto das Emas.'
  )
on conflict (url) do nothing;

insert into public.ecclesiastical_jurisdictions (
  slug,
  name,
  canonical_type,
  tradition,
  country_code,
  status,
  erected_year,
  description,
  official_url,
  primary_source_id
)
values
  (
    'santa-se',
    'Santa Sé',
    'holy_see',
    'latin',
    'VA',
    'active',
    null,
    'Sé Apostólica e governo central da Igreja Católica.',
    'https://www.vatican.va/',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://www.vaticanstate.va/en/state-and-government/general-informations/origins-and-characteristic.html'
    )
  ),
  (
    'provincia-eclesiastica-brasilia',
    'Província Eclesiástica de Brasília',
    'ecclesiastical_province',
    'latin',
    'BR',
    'active',
    1966,
    'Província presidida pelo Arcebispo Metropolitano de Brasília.',
    'https://www.cnbb.org.br/a-estrutura-administrativa-e-pastoral-da-cnbb-tem-uma-matriz-e-18-unidades-regionais/',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://www.cnbb.org.br/a-estrutura-administrativa-e-pastoral-da-cnbb-tem-uma-matriz-e-18-unidades-regionais/'
    )
  ),
  (
    'arquidiocese-brasilia',
    'Arquidiocese de Brasília',
    'metropolitan_archdiocese',
    'latin',
    'BR',
    'active',
    1966,
    'Sé metropolitana da Província Eclesiástica de Brasília.',
    'https://arqbrasilia.com.br/',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/paroquias/'
    )
  ),
  (
    'diocese-formosa',
    'Diocese de Formosa',
    'diocese',
    'latin',
    'BR',
    'active',
    1979,
    'Diocese sufragânea da Província Eclesiástica de Brasília.',
    'https://diocesedeformosa.com.br/',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://diocesedeformosa.com.br/paroquia/catedralnossasenhoraimaculadaconceicao/'
    )
  ),
  (
    'paroquia-santuario-fatima-brasilia',
    'Paróquia Santuário Nossa Senhora de Fátima',
    'parish',
    'latin',
    'BR',
    'active',
    1958,
    'Paróquia do Vicariato Centro da Arquidiocese de Brasília.',
    'https://arqbrasilia.com.br/todas_paroquias/nossa-senhora-de-fatima/',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/todas_paroquias/nossa-senhora-de-fatima/'
    )
  ),
  (
    'paroquia-sao-rafael-arcanjo-recanto',
    'Paróquia São Rafael Arcanjo',
    'parish',
    'latin',
    'BR',
    'active',
    2023,
    'Paróquia do Recanto das Emas, criada em 12 de março de 2023.',
    'https://arqbrasilia.com.br/todas_paroquias/paroquia-sao-rafael-arcanjo/',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/todas_paroquias/paroquia-sao-rafael-arcanjo/'
    )
  )
on conflict (slug) do nothing;

insert into public.ecclesiastical_relations (
  subject_jurisdiction_id,
  object_jurisdiction_id,
  relation_type,
  valid_from_year,
  primary_source_id
)
values
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'arquidiocese-brasilia'),
    (select id from public.ecclesiastical_jurisdictions where slug = 'provincia-eclesiastica-brasilia'),
    'metropolitan_of',
    1966,
    (
      select id from public.ecclesiastical_sources
      where url = 'https://www.cnbb.org.br/a-estrutura-administrativa-e-pastoral-da-cnbb-tem-uma-matriz-e-18-unidades-regionais/'
    )
  ),
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'diocese-formosa'),
    (select id from public.ecclesiastical_jurisdictions where slug = 'arquidiocese-brasilia'),
    'suffragan_of',
    1979,
    (
      select id from public.ecclesiastical_sources
      where url = 'https://www.cnbb.org.br/a-estrutura-administrativa-e-pastoral-da-cnbb-tem-uma-matriz-e-18-unidades-regionais/'
    )
  ),
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'paroquia-santuario-fatima-brasilia'),
    (select id from public.ecclesiastical_jurisdictions where slug = 'arquidiocese-brasilia'),
    'subdivision_of',
    1958,
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/todas_paroquias/nossa-senhora-de-fatima/'
    )
  ),
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'paroquia-sao-rafael-arcanjo-recanto'),
    (select id from public.ecclesiastical_jurisdictions where slug = 'arquidiocese-brasilia'),
    'subdivision_of',
    2023,
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/todas_paroquias/paroquia-sao-rafael-arcanjo/'
    )
  )
on conflict (
  subject_jurisdiction_id,
  object_jurisdiction_id,
  relation_type,
  valid_from_year
) do nothing;

insert into public.ecclesiastical_sites (
  jurisdiction_id,
  slug,
  name,
  site_type,
  address,
  locality,
  admin_area,
  country_code,
  location,
  min_zoom,
  display_rank,
  valid_from_year,
  official_url,
  location_accuracy,
  primary_source_id,
  is_primary
)
values
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'santa-se'),
    'santa-se-vaticano',
    'Santa Sé',
    'apostolic_see',
    '00120 Cidade do Vaticano',
    'Cidade do Vaticano',
    null,
    'VA',
    extensions.st_point(12.45394, 41.90216)::extensions.geography,
    0,
    1,
    null,
    'https://www.vatican.va/',
    'exact',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://www.vaticanstate.va/en/state-and-government/general-informations/origins-and-characteristic.html'
    ),
    true
  ),
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'arquidiocese-brasilia'),
    'catedral-metropolitana-brasilia',
    'Catedral Metropolitana Nossa Senhora Aparecida',
    'cathedral',
    'Esplanada dos Ministérios, Lote 12',
    'Brasília',
    'Distrito Federal',
    'BR',
    extensions.st_point(-47.8755465, -15.7983445)::extensions.geography,
    3.2,
    10,
    1970,
    'https://arqbrasilia.com.br/paroquias/',
    'exact',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/paroquias/'
    ),
    true
  ),
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'diocese-formosa'),
    'catedral-imaculada-conceicao-formosa',
    'Catedral Nossa Senhora Imaculada Conceição',
    'cathedral',
    'Praça da Matriz, s/n',
    'Formosa',
    'Goiás',
    'BR',
    extensions.st_point(-47.3373, -15.5453)::extensions.geography,
    5.3,
    20,
    1979,
    'https://diocesedeformosa.com.br/paroquia/catedralnossasenhoraimaculadaconceicao/',
    'geocoded_address',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://diocesedeformosa.com.br/paroquia/catedralnossasenhoraimaculadaconceicao/'
    ),
    true
  ),
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'paroquia-santuario-fatima-brasilia'),
    'santuario-nossa-senhora-fatima-brasilia',
    'Santuário Nossa Senhora de Fátima',
    'shrine',
    'SGAS 906, lotes 10/11, Asa Sul',
    'Brasília',
    'Distrito Federal',
    'BR',
    extensions.st_point(-47.9045508, -15.8051117)::extensions.geography,
    11.2,
    40,
    1958,
    'https://arqbrasilia.com.br/todas_paroquias/nossa-senhora-de-fatima/',
    'geocoded_address',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/todas_paroquias/nossa-senhora-de-fatima/'
    ),
    true
  ),
  (
    (select id from public.ecclesiastical_jurisdictions where slug = 'paroquia-sao-rafael-arcanjo-recanto'),
    'igreja-sao-rafael-arcanjo-recanto',
    'Igreja São Rafael Arcanjo',
    'parish_church',
    'Avenida Recanto das Emas, Quadra 309',
    'Recanto das Emas',
    'Distrito Federal',
    'BR',
    extensions.st_point(-48.1036, -15.9233)::extensions.geography,
    11.2,
    50,
    2023,
    'https://arqbrasilia.com.br/todas_paroquias/paroquia-sao-rafael-arcanjo/',
    'geocoded_address',
    (
      select id from public.ecclesiastical_sources
      where url = 'https://arqbrasilia.com.br/todas_paroquias/paroquia-sao-rafael-arcanjo/'
    ),
    true
  )
on conflict (slug) do nothing;
